// Command gen-crd writes the NodeHealthReport CRD, generated from the Verdict
// type, into the Helm chart.
package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/nathanwebb/tropis/pkg/k8s"
)

func main() {
	out := flag.String("o", "deploy/helm/tropis/crds/tropis.io_nodehealthreports.yaml", "output file")
	flag.Parse()
	b, err := k8s.CRDYAML()
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-crd: %v\n", err)
		os.Exit(1)
	}
	header := []byte("# Generated by `go run ./hack/gen-crd` from pkg/schema. Do not edit.\n")
	if err := os.WriteFile(*out, append(header, b...), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-crd: %v\n", err)
		os.Exit(1)
	}
}
